#########################################
# Copyright (C) 2016 Project Bonfire    #
#                                       #
# This file is automatically generated! #
#             DO NOT EDIT!              #
#########################################

vlib work

# Include files and compile them
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/arbiter_in.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/arbiter_out.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/allocator.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/LBDR.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/xbar.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/FIFO_one_hot_credit_based.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/Router_32_bit_credit_based.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/Test/TB_Package_32_bit_credit_based.vhd"
vcom "network_4x4_credit_based.vhd"
vcom "network_4x4_NI_Test_Rand_credit_based_tb.vhd"

# Start the simulation
vsim work.tb_network_4x4

# Draw waves
do wave_4x4.do
# Run the simulation
vcd file wave.vcd
vcd add -r -optcells /*
run 11000 ns
vcd flush
