simulation_config:
    network_size: 2
    simulation_time: 10us

network_template: ni_template

tb_template: ni_tb_template

router: Router_32_bit_credit_based_packet_drop_classifier_SHMU

ni_pe: NI_FT_shallow
