#########################################
# Copyright (C) 2016 Project Bonfire    #
#                                       #
# This file is automatically generated! #
#             DO NOT EDIT!              #
#########################################

vlib work

# Include files and compile them
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Processor/mlite_pack.vhd"

vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/allocator.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/arbiter_in.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/arbiter_out.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/counter_threshold.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/ParityChecker_for_LBDR.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/FIFO_one_hot_credit_based_packet_drop_classifier_support.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/LBDR_packet_drop.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/xbar.vhd"
vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/Router/Router_32_bit_credit_based_packet_drop_classifier_SHMU.vhd"

vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/RTL/NI/NI_FT_shallow.vhd"

vcom "/media/Data/workspace/upgrading_Bonfire/Bonfire_merging/Test/TB_Package_32_bit_credit_based_NI.vhd"

vcom "network_2x2_packet_drop_SHMU_credit_based.vhd"
vcom "network_2x2_NI_Test_packet_drop_Rand_SHMU_credit_based_tb.vhd"

# Start the simulation
vsim work.tb_network_2x2

# Draw waves
do wave_2x2.do
# Run the simulation
vcd file wave.vcd
vcd add -r -optcells /*
run 350000 ns
vcd flush

# Exit Modelsim after simulation
exit
